### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by selivan2203** [yandex/YandexDriver#21]
Здравствуйте. Под Windows не будет больше обновлений?

**Comment by shorrcan** [comment]
Поддерживаю...
"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 120 Current browser version is 122.0.6261.899"

**Comment by ipsissimus** [comment]
Поддерживаю, браузер обновился на 24.4 а версии драйвера нигде не найти, как так можно и что, выходит Яндекс Браузер больше не использовать?

**Comment by PetrovVadim** [comment]
Сейчас выложим, спасибо за сигнал.
Поддерживать будем и дальше.
