### ISSUE TITLE
Publish binaries for all supported platforms for every release

### ISSUE THREAD

**Issue by vania-pooh** [yandex/YandexDriver#3]
Need to have Mac, Win and Linux binaries for every release. Right now some releases have only Windows binaries, some other - only Linux binaries and so on.

**Comment by ruescar** [comment]
I agree with @vania-pooh. Currently it's not easy to automate the retrieval of the latest driver version for a given platform.

**Comment by ruescar** [comment]
Also, it would really facilitate things to align the version names across `tag_name` and `browser_download_url`. Either not using patch versions or including the patch version in the `tag_name` too.

**Comment by PetrovVadim** [comment]
We publish binaries only for the first major version on win and mac. Eg 22.3.0
But we have exception for linux, because we don't publish the first major version of yandex browser for linux. Eg 22.3.1
Sorry.
