### ISSUE TITLE
Ошибка при использовании драйвера

### ISSUE THREAD

**Issue by Freem18** [yandex/YandexDriver#7]
При использовании драйвера версии v20.8.3-stable для Linux возникает ошибка, а именно: error: "unknown error"
message: "unknown error: cannot find Chrome binary"
stacktrace: "#0 0x55dc8dd9d049 <unknown>

Использовалась версия браузера 20.9.3 из репозитория https://repo.yandex.ru/yandex-browser/deb/

Прошу пояснить, в чем проблема, если в несовместимости драйвера и версии браузера, то какую версию драйвера необходимо использовать?  Версия v20.8.3-stable для Linux бралась как последняя собранная в репозитории.

**Comment by PetrovVadim** [comment]
Версии должны соответствовать. Попробуйте версию 20.11.3 браузера и драйвера.
