### ISSUE TITLE
Версия yandexdriver не соответствует последней установленной версии google chrome

### ISSUE THREAD

**Issue by EvgenyRomakov** [yandex/YandexDriver#8]
Коллеги, подскажите пжл, что делать?

**Это мой код:**
from selenium import webdriver
options = webdriver.ChromeOptions()
binary_yandex_driver_file = 'c:\\Users\Admin\Documents\IT\yandexdriver\yandexdriver.exe' 

driver = webdriver.Chrome(binary_yandex_driver_file, options=options)
driver.get(URL)

**Возникает следующая ошибка:**
SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 88
Current browser version is 87.0.4280.141 with binary path C:\Users\Admin\AppData\Local\Yandex\YandexBrowser\Application\browser.exe

Если я правильно понимаю, версия yandexdriver старше версии chrome. Если было бы наоборот, я бы просто обновил Chrome. А тут как быть?

**Comment by PetrovVadim** [comment]
Можно скачать более старую версию драйвера.
87 это 20.12.х версии.
Вот: https://github.com/yandex/YandexDriver/releases/tag/v20.12.0-stable
