### ISSUE TITLE
Extensions cannot be installed with yandex driver

### ISSUE THREAD

**Issue by Phlegethonyarre** [yandex/YandexDriver#9]
Platform: win/unix
Extension: Any (Crypto Pro Cades for example)
Tools: java + selenide (selenium)
Yandexdriver version: latest (yandexdriver-21.3.0.673)
Code example:
```
@ParametersAreNonnullByDefault
public class CustomWebDriverProvider implements WebDriverProvider {

    @Override
    @CheckReturnValue
    @Nonnull
    public ChromeDriver createDriver(DesiredCapabilities capabilities) {
        ChromeOptions options = new ChromeOptions();
        options.addArguments("load-extension=driver/epebfcehmdedogndhlcacafjaacknbcm/1.2.8_0/");
//     options.addExtensions(new File("driver/epebfcehmdedogndhlcacafjaacknbcm-1.2.8.crx"));
        return new ChromeDriver(options);
    }
}
```

Problem: extension does not appear as installed in any way.
Tested with chromedriver and operadriver. Both ways of installing work well with these drivers, but not with yandexdriver.

**Comment by AleksKarl** [comment]
Hi I have the same problem, have you made any progress on this issue?

**Comment by PetrovVadim** [comment]
Hello!
You can use beta version of Yandex.Browser: https://browser.yandex.ru/beta/
We decided that it isn't secure to allow to install extensions in production version.
